//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftSepeti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bayisatisTable
    {
        public int id { get; set; }
        public int bayiid { get; set; }
        public int musteriid { get; set; }
        public int bayiurunleriid { get; set; }
        public System.DateTime tarih { get; set; }
        public double kar { get; set; }
        public int satisadet { get; set; }
    
        public virtual bayiTable bayiTable { get; set; }
        public virtual bayiurunlerTable bayiurunlerTable { get; set; }
        public virtual musteriTable musteriTable { get; set; }
    }
}
