//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftSepeti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class bayiTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bayiTable()
        {
            this.bayisatisTable = new HashSet<bayisatisTable>();
            this.bayiurunlerTable = new HashSet<bayiurunlerTable>();
            this.siparisTable = new HashSet<siparisTable>();
        }
    
        public int id { get; set; }
        public string ulke { get; set; }
        public string sehir { get; set; }
        public string bayiad { get; set; }
        public string sifre { get; set; }
        public string adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bayisatisTable> bayisatisTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bayiurunlerTable> bayiurunlerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisTable> siparisTable { get; set; }
    }
}
