//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftSepeti.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class liftTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public liftTable()
        {
            this.bayiurunlerTable = new HashSet<bayiurunlerTable>();
            this.siparisTable = new HashSet<siparisTable>();
        }
    
        public int id { get; set; }
        public int modelid { get; set; }
        public int adet { get; set; }
        public double fiyat { get; set; }
        public int bakimperiyot { get; set; }
        public string resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bayiurunlerTable> bayiurunlerTable { get; set; }
        public virtual modelTable modelTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siparisTable> siparisTable { get; set; }
    }
}
